### ISSUE TITLE
1st Year 

### ISSUE THREAD

**Issue by Priyanshi-Rai** [Coding-Connoisseurs/demo#2]
#

> You can edit and add a description too.
> Now make changes and add that pr here so that we can merge it.

Okay

**Comment by pr0PM** [comment]
You can edit and add a description too.
Now make changes and add that pr here so that we can merge it.

**Comment by Priyanshi-Rai** [comment]
## JUST FOR FUN
Hey folks, 
Here I m gonna introducing myself with all the wrong info: 

## DESCRIPTION
We are going to write everything as a negative or opposite sentences 
e.g. : 
If I write
I love ladyfinger .
it means the opposite of it  :P

## Disclaimer  :- 

- [ ] It's just for fun. 
- [ ] No human rights are violated(only Hoomans).
- [ ] I'm not at all responsible for anyone's sentiments.
